Downgrade Sphinx to compatible version 4.0.3
fedora-infra/anitya pull request #1149
Opened 2021-07-26 18:37 UTC by oturpe

On Sphinx 4.1.1, Tox `docs` task fails due to following kind of error:
    
```
autoflask>:1:Problem in http domain: field is supposed to use role 'obj', but that role is not in the domain.
```
    
This does not happen on Sphinx 4.0.3, so downgrading to that.
    
Fixes #1148 

Also `.gitignore` improvement.

2021-07-26 18:49 UTC, Zlopez requested changes
Remove the docs/images/database.png, this file should be uploaded only if there is any change in database.

Also don't ignore the folder that contains it, otherwise the images will be missing in the documentation. We could probably prevent that by adding the ./generate_database_image script to Makefile for docs building.

2021-07-26 18:49 UTC, Zlopez commented on .gitignore
> +docs/images/
We don't want to ignore this folder, otherwise the database diagram is missing in documentation on readthedocs.

2021-07-26 18:59 UTC, Zlopez approved these changes

2021-07-26 19:00 UTC, abitrolly commented
> Remove the docs/images/database.png, this file should be uploaded only if there is any change in database.

The best way probably would be to generate the image in reproducible way.

2021-07-26 19:06 UTC, merged

2021-07-26 19:07 UTC, oturpe commented
> Remove the docs/images/database.png, this file should be uploaded only if there is any change in database.
> 
> Also don't ignore the folder that contains it, otherwise the images will be missing in the documentation. We could probably prevent that by adding the ./generate_database_image script to Makefile for docs building.

Ok, I dropped the commit related to these.
It is just that when you run `tox -e docs`,
that file changes and Git starts showing it as modified.
I took this a case of missing `.gitignore`,
now I see that things were intentionally set up this way.

Btw. you could both commit the file **and** have it in `.gitignore`.
That works, but because it is not a common pattern,
it might just cause more confusion than
an autogenerated file showing up in `git status` as modified does.

2021-07-26 19:39 UTC, abitrolly commented
> It is just that when you run tox -e docs, that file changes and Git starts showing it as modified.

It appears that on my F34 the `docs/images/database.png` is same even if I regenerate it. How do you run it? Can you attach your version here?

2021-07-26 20:02 UTC, Zlopez commented
The output is same, but I think that the metadata are different, so this is why git thinks that this is always a new version.

2021-07-26 20:37 UTC, abitrolly commented
Where the metadata is stored?

2021-07-26 21:01 UTC, Zlopez commented
Directly in PNG, just check the the file with `exiftool`
```
$ exiftool database.png 
ExifTool Version Number         : 12.26
File Name                       : database.png
Directory                       : .
File Size                       : 31 KiB
File Modification Date/Time     : 2021:02:21 13:33:25+01:00
File Access Date/Time           : 2021:07:25 09:48:01+02:00
File Inode Change Date/Time     : 2021:05:06 12:30:19+02:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 453
Image Height                    : 719
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Background Color                : 255 255 255
Image Size                      : 453x719
Megapixels                      : 0.326
```

2021-07-27 14:44 UTC, abitrolly commented
@Zlopez no, these fields are not stored in .png
```
File Modification Date/Time     : 2021:02:21 13:33:25+01:00
File Access Date/Time           : 2021:07:25 09:48:01+02:00
File Inode Change Date/Time     : 2021:05:06 12:30:19+02:00
```
I regenerated the image from scratch and `git` doesn't detect any changes. There must be something else here. Perhaps a problem with database.

![database](https://user-images.githubusercontent.com/8781107/127174788-a18c4773-05cd-437a-b0b5-c7c6c5f22e08.png)

2021-07-28 09:19 UTC, Zlopez commented
Hm, in this case I'm not sure why git is thinking that the image is sometime new even if there wasn't any change in the database.