Social sqlalchemy
fedora-infra/anitya pull request #1726
Opened 2024-03-08 10:36 UTC by NyuydineBill

Description:
This pull request adds optional instructions for configuring social_sqlalchemy, a package for SQLAlchemy storage support for Python Social Auth, in Flask applications. It provides a code example demonstrating how to set up social_sqlalchemy in a Flask app, including configuring the SQLAlchemy database and initializing social_sqlalchemy. Additionally, it includes a note on starting the development web server with Flask.

Purpose:
The purpose of this pull request is to enhance the contributing guidelines by providing guidance on integrating social_sqlalchemy with Flask applications for OAuth and OAuth2 authentication. This addition aims to assist contributors who may want to use social_sqlalchemy in their Flask projects, thereby improving the overall development experience for Anitya contributors.

Changes Made:
Added instructions for configuring social_sqlalchemy in Flask applications to the contributing.rst file.
Included a code example demonstrating the setup process for social_sqlalchemy.
Updated the Python Virtualenv section of the contributing.rst file to include these instructions.
Testing:
These instructions were tested locally by following the provided steps to configure social_sqlalchemy in a Flask application within a Python virtual environment. The Flask development server was started successfully, indicating that the setup process was correct and functional.

Related Issue:
#1723

2024-03-08 11:37 UTC, Zlopez commented
And also don't forget to add news file for the update. See https://anitya.readthedocs.io/en/latest/contributing.html#release-notes for more info

2024-03-08 13:37 UTC, Zlopez requested changes
Still some changes required, but getting there.

2024-03-08 13:37 UTC, Zlopez commented on docs/contributing.rst
> +in config.py::
```suggestion
in `anitya/config.py`::
```

2024-03-08 13:37 UTC, Zlopez commented on news/1723.other
Ideally this should be a one line file.

2024-03-08 18:16 UTC, NyuydineBill commented on news/1723.other
corrected

2024-03-11 14:53 UTC, Zlopez commented
Thanks for fixing the tests! Could you now squash the commits so there is only one commit message?

2024-03-12 14:00 UTC, closed without merging