Added version patterns to user-guide.rst
fedora-infra/anitya pull request #1747
Opened 2024-03-25 12:19 UTC by vidit-maheshwari

## Pull Request: Add Version Pattern Documentation to User Guide

### Issue

Fixes #1604 

### Description

This pull request adds documentation for the version pattern field in the user guide. The version pattern field is essential for extracting and matching version numbers from project releases, and it allows users to specify the format of version numbers using regular expressions. This documentation clarifies the usage of various pattern tokens such as `YYYY`, `YY`, `MM`, `WW`, `DD`, etc., along with their examples and notes on usage.

### Changes Made

- Added a new section titled "Version Pattern" to the user guide (`user-guide.rst`).
- Provided detailed explanations and examples for each pattern token (`YYYY`, `YY`, `MM`, `WW`, `DD`, etc.).
- Included notes on traditional version numbering, the relative nature of short and zero-padded years, and the mutual exclusivity of weeks with months/days.

### Testing Done

- Reviewed the changes locally to ensure accuracy and clarity.
- Checked for formatting and consistency with existing documentation.

### Additional Notes

- This documentation enhancement aims to improve usability and clarity for users configuring the version pattern field.
- Any feedback or suggestions for improvement are welcome.

---
*Please review and merge this pull request at your earliest convenience. Thank you!*

2024-03-25 12:21 UTC, vidit-maheshwari commented
@Zlopez Everything looks fine now and i have also ran all the tests locally before making the PR and everything looks clean.
Kindly review this PR

2024-03-25 12:36 UTC, Zlopez requested changes
Needs few changes.

2024-03-25 12:36 UTC, Zlopez commented on docs/user-guide.rst
> +project releases. It allows for specifying the format of version numbers
```suggestion
project releases. It allows for specifying the format for calendar versioning scheme using following patterns.
```

2024-03-25 12:36 UTC, Zlopez commented on docs/user-guide.rst
> +using regular expressions.
```suggestion
```

2024-03-25 12:36 UTC, Zlopez commented on docs/user-guide.rst
> +Patterns -
You should add empty line after this, otherwise the list will not work correctly.

2024-03-25 12:36 UTC, Zlopez commented on docs/user-guide.rst
> +Notes:
Use notes from restructured text https://sublime-and-sphinx-guide.readthedocs.io/en/latest/notes_warnings.html#notes

2024-03-25 12:36 UTC, Zlopez commented on docs/user-guide.rst
> +The version pattern is used to extract and match version numbers from
```suggestion
The version pattern is used to define how the calendar version should be parsed and how they will be sorted. 
```

2024-03-25 13:55 UTC, vidit-maheshwari commented
@Zlopez i have made the required changes as you instructed. Kindly review if needed any changes

2024-03-25 15:26 UTC, Zlopez commented
The documentation seems OK now, but you introduced error to docs CI, could you fix that?

2024-03-26 08:34 UTC, vidit-maheshwari commented
@Zlopez I have resolved the build issue, Kindly review the PR.

2024-03-26 10:39 UTC, Zlopez commented
@vidit-maheshwari Thanks for resolving the failing tests. Could you just squash the commits? We don't need 6 commits for one documentation change :-)

2024-03-26 17:09 UTC, closed without merging