Fixing python virtualenv
fedora-infra/anitya pull request #1762
Opened 2024-04-19 19:38 UTC by anshikavashistha

2024-04-19 19:41 UTC, anshikavashistha commented
@Zlopez Have a look on this PR?
I have some fault in my VMware due to which I would not be able to make changes in that current PR.

2024-04-22 10:22 UTC, Zlopez requested changes
Some things are still not correct. Also you have a conflict in this PR

2024-04-22 10:22 UTC, Zlopez commented on anitya/lib/plugins.py
> +import importlib
This import isn't necessary.

2024-04-22 10:22 UTC, Zlopez commented on createdb.py
> +import importlib
This import isn't necessary.

2024-11-22 12:30 UTC, closed without merging