feat: add cpe and purl to project
fedora-infra/anitya pull request #1827
Opened 2024-10-17 16:05 UTC by antonleviathan

@Zlopez I just wanted to throw up a draft of the PR for https://github.com/fedora-infra/anitya/issues/1821.

I haven't set up my development environment so I still have to test the code but this *should* work. Lmk if you see any issues with the PR so I can address them.

2024-10-17 16:05 UTC, antonleviathan commented
Oh I forgot to update the "edit" and "new" pages for projects. Derp.

2024-10-18 08:31 UTC, Zlopez requested changes
This looks like a good base for the PR, but it's still missing a lot.

* news file for changelog
* Documentation for new fields
* Database migration script
* And plenty of tests

2024-10-18 08:31 UTC, Zlopez commented on anitya/templates/project.html
> +        <div class="list-group-item">
Could you show how this is looking on the UI?

2024-10-18 08:31 UTC, Zlopez commented on anitya/tests/test_project.py
> +    def test_project_by_cpe_2_3(self):
There needs to be test for API calls as well.

2024-10-18 08:31 UTC, Zlopez commented on anitya/templates/project_new.html
> +            <tr id="cpe_2_3_row">
Adding new fields here needs to be reflected in `anitya.ui.new_project`, `anitya.forms.ProjectForm` and `anitya.api_v2.ProjectsResource.post`.

2024-10-18 08:31 UTC, Zlopez commented on anitya/api.py
> +def api_get_project_by_cpe_2_3(cpe2_3):
This should be in `api_v2`. Don't add things to `api`.

2024-10-18 08:31 UTC, Zlopez commented on anitya/tests/test_project.py
> +    def test_project_by_cpe_2_3(self):
And also models.

2025-01-06 05:45 UTC, closed without merging